import type {TrackMetadata} from '../../types';

/**
 * Bundled track catalog with real BPMs.
 * Audio files live in assets/tracks/ and are bundled via Metro require().
 */
export const LOCAL_TRACKS: TrackMetadata[] = [
  {
    id: 'local-take-it',
    title: 'Take It',
    artist: 'Unknown',
    album: null,
    durationSeconds: 180,
    bpm: 123,
    url: require('../../../../../assets/tracks/take_it_123bpm.mp3'),
    artworkUrl: null,
    genre: null,
  },
  {
    id: 'local-stop-it',
    title: 'Stop It (Original Mix)',
    artist: 'Unknown',
    album: null,
    durationSeconds: 180,
    bpm: 125,
    url: require('../../../../../assets/tracks/stop_it_125bpm.mp3'),
    artworkUrl: null,
    genre: null,
  },
  {
    id: 'local-human',
    title: 'Human (feat. Echoes)',
    artist: 'Unknown',
    album: null,
    durationSeconds: 180,
    bpm: 126,
    url: require('../../../../../assets/tracks/human_126bpm.mp3'),
    artworkUrl: null,
    genre: null,
  },
  {
    id: 'local-billie',
    title: 'Billie (loving arms)',
    artist: 'Unknown',
    album: null,
    durationSeconds: 180,
    bpm: 130,
    url: require('../../../../../assets/tracks/billie_130bpm.mp3'),
    artworkUrl: null,
    genre: null,
  },
  {
    id: 'local-leavemealone',
    title: 'leavemealone',
    artist: 'Unknown',
    album: null,
    durationSeconds: 180,
    bpm: 130,
    url: require('../../../../../assets/tracks/leavemealone_130bpm.mp3'),
    artworkUrl: null,
    genre: null,
  },
  {
    id: 'local-victory-lap',
    title: 'Victory Lap',
    artist: 'Unknown',
    album: null,
    durationSeconds: 180,
    bpm: 130,
    url: require('../../../../../assets/tracks/victory_lap_130bpm.mp3'),
    artworkUrl: null,
    genre: null,
  },
  {
    id: 'local-places-to-be',
    title: 'places to be',
    artist: 'Unknown',
    album: null,
    durationSeconds: 180,
    bpm: 132,
    url: require('../../../../../assets/tracks/places_to_be_132bpm.mp3'),
    artworkUrl: null,
    genre: null,
  },
  {
    id: 'local-jungle',
    title: 'Jungle',
    artist: 'Unknown',
    album: null,
    durationSeconds: 180,
    bpm: 134,
    url: require('../../../../../assets/tracks/jungle_134bpm.mp3'),
    artworkUrl: null,
    genre: null,
  },
  {
    id: 'local-sunsleeper',
    title: 'Sunsleeper',
    artist: 'Unknown',
    album: null,
    durationSeconds: 180,
    bpm: 134,
    url: require('../../../../../assets/tracks/sunsleeper_134bpm.mp3'),
    artworkUrl: null,
    genre: null,
  },
  {
    id: 'local-the-days',
    title: 'The Days (NOTION Remix)',
    artist: 'Unknown',
    album: null,
    durationSeconds: 180,
    bpm: 135,
    url: require('../../../../../assets/tracks/the_days_notion_remix_135bpm.mp3'),
    artworkUrl: null,
    genre: null,
  },
  {
    id: 'local-kisses',
    title: 'Kisses (feat. bbyclose)',
    artist: 'Unknown',
    album: null,
    durationSeconds: 180,
    bpm: 140,
    url: require('../../../../../assets/tracks/kisses_140bpm.mp3'),
    artworkUrl: null,
    genre: null,
  },
  {
    id: 'local-know-me',
    title: 'Know Me',
    artist: 'Unknown',
    album: null,
    durationSeconds: 180,
    bpm: 140,
    url: require('../../../../../assets/tracks/know_me_140bpm.mp3'),
    artworkUrl: null,
    genre: null,
  },
  {
    id: 'local-rumble',
    title: 'Rumble',
    artist: 'Unknown',
    album: null,
    durationSeconds: 180,
    bpm: 140,
    url: require('../../../../../assets/tracks/rumble_140bpm.mp3'),
    artworkUrl: null,
    genre: null,
  },
  {
    id: 'local-rowdy',
    title: 'Rowdy (BLAOW!)',
    artist: 'Unknown',
    album: null,
    durationSeconds: 180,
    bpm: 174,
    url: require('../../../../../assets/tracks/rowdy_174bpm.mp3'),
    artworkUrl: null,
    genre: null,
  },
];

export const MIN_BPM = 123;
export const MAX_BPM = 174;
export const TRACK_COUNT = LOCAL_TRACKS.length;
